version: '3'
services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
    restart: always
    ports:
      - "9000:9000"
