apiVersion: v1
kind: Namespace
metadata:
  name: zeromq-poc
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeromq-poc
  namespace: zeromq-poc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: zeromq-poc.k8s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zeromq-poc-client
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zeromq-poc-client
  name: zeromq-poc-client
  namespace: zeromq-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeromq-poc-client
  template:
    metadata:
      labels:
        app:
          zeromq-poc-client
    spec:
      containers:
        - name: zeromq-poc-client
          image: asaf/zeromq-poc-client
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DEV_WEBSOCKET_PORT
              value: $(ZEROMQ_POC_CLIENT_EXTERNAL_SERVICE_PORT_HTTP)
            - name: DEBUG
              value: "express:*"
---
apiVersion: v1
kind: Service
metadata:
  name: zeromq-poc-client-external
  namespace: zeromq-poc
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 80
  selector:
    app: zeromq-poc-client
---
apiVersion: v1
kind: Service
metadata:
  name: zeromq-poc-client
  namespace: zeromq-poc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: zeromq-poc-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zeromq-poc-server
  name: zeromq-poc-server
  namespace: zeromq-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeromq-poc-server
  template:
    metadata:
      labels:
        app: zeromq-poc-server
    spec:
      containers:
        - name: zeromq-poc-server
          image: asaf/zeromq-poc-server
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: zeromq-poc-server-external
  namespace: zeromq-poc
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: zeromq-poc-server
